nu:
  ndw:
    nls:
      springboot:
        messaging:
          broker-uri: amqp://guest:guest@localhost:5672?heartbeat=300
          receive:
            - queue: integration_test_accessibility_routing_network_updated
              expectedEventTypes:
                - ACCESSIBILITY_ROUTING_NETWORK_UPDATED
              eventSubjectType: ACCESSIBILITY_ROUTING_NETWORK
              initialize: DECLARE

graphhopper:
  dir: ../../.tmp/graphhopper
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nls-maps?ApplicationName=nls-accessibility-map-graphhopper-job&stringtype=unspecified
    username: nls-maps
    password: nls-maps


