management:
  datadog:
    metrics:
      export:
        enabled: false

  observations:
    annotations:
      enabled: false
nu:
  ndw:
    nls:
      springboot:
        messaging:
          broker-uri: amqp://guest:guest@localhost:5672?heartbeat=300
      accessibilitymap:
        trafficsignclient:
          api:
            url: https://data.ndw.nu/api/rest/static-road-data/traffic-signs/v4
            current-state-path: /current-state
        jobs:
          generate:
            root-generation-destination: ../../map-generation-destination
            prettyPrintJson: true
logging:
  level:
    root: INFO
    nu.ndw.nls: DEBUG
graphhopper:
  dir: graphhopper
spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/nls-maps?ApplicationName=nls-accessibility-map-generator-jobs&stringtype=unspecified
    username: nls
    password: JrUYIqvWaRik4c6IUWeo172J1kawqD

