nu:
  ndw:
    nls:
      springboot:
        messaging:
          broker-uri: amqp://guest:guest@localhost:5672?heartbeat=300
      accessibilitymap:
        trafficsignclient:
          api:
            base-url: http://localhost:8888/api/rest/static-road-data/traffic-signs/v4
            town-code: GM0307

logging:
  level:
    root: INFO
    nu.ndw.nls: DEBUG
graphhopper:
  dir: graphhopper
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nls-maps?ApplicationName=nls-accessibility-map-graphhopper-job&stringtype=unspecified
    username: nls-maps
    password: nls-maps
