nu:
  ndw:
    nls:
      springboot:
        messaging:
          broker-uri: amqp://guest:guest@localhost:5672?heartbeat=300
#          Not part of the application, but we use this to setup some queues on which we will receive the produced
#          messsages
          receive:
              - queue: nls_map_loader_fcd_retrieved
                routingKey: ndw.nls.fcd.retrieved
                expectedEventTypes:
                  - FCD_RETRIEVED_EVENT

graphhopper:
  dir: ../../graphhopper
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nls-maps?ApplicationName=nls-accessibility-map-graphhopper-job&stringtype=unspecified
    username: nls-maps
    password: nls-maps


