graphhopper:
  dir: /application/graphhopper
  network-name: accessibility_latest
  with-traffic-signs: true
  publish-events: true

jooq:
  schema-validation:
    schema-severity:
      nwb: ERROR
    packages-to-scan:
      - nu.ndw.nls.db.nwb.jooq.generated

org:
  jooq:
    no-logo: true
spring:
  application:
    name: nls-accessibility-map-graphhopper-job
  # Disables netty webserver startup
  main:
    web-application-type: none
  config:
    import: "optional:configtree:/application/config/configtree/"
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SELECT 1;
      idle-timeout: 60000
      max-lifetime: 120000
      minimum-idle: 1
      auto-commit: false
  jmx:
    enabled: false
  jooq:
    sql-dialect: Postgres

nu:
  ndw:
    nls:
      accessibilitymap:
        trafficsignclient:
          api:
            url: https://data.ndw.nu/api/rest/static-road-data/traffic-signs/v4
            current-state-path: /current-state
      springboot:
        messaging:
          publish:
            - routingKey: ndw.nls.accessibility.routing.network.updated
              expectedEventType: ACCESSIBILITY_ROUTING_NETWORK_UPDATED
          receive:
            - queue: nls_accessibility_map_graphhopper_job_no_traffic_sign_nwb_imported
              routingKey: ndw.nls.nwb.imported
              expectedEventTypes:
                - NWB_IMPORTED_EVENT
management:
  observations:
    annotations:
      enabled: true

