apiVersion: v1
kind: ConfigMap
metadata:
  name: wiremock-import
data:
{{- $files := .Files.Glob "data/wiremock/mappings/*.json" }}
{{- range $path, $content := $files }}
  {{ base $path }}: |-
{{ $content | toString | indent 4 }}
{{- end }}
