broker:
  uri: amqp://guest:guest@localhost:5672?heartbeat=300
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nls-maps?ApplicationName=nls-accessibility-map-jobs&stringtype=unspecified
    username: nls-maps
    password: nls-maps
