nu:
  ndw:
    nls:
      springboot:
        messaging:
          broker-uri: amqp://guest:guest@nls-rabbitmq:5672?heartbeat=300
      accessibilitymap:
        trafficsignclient:
          api:
            base-url: http://traffic-sign-api-stub:8080/api/rest/static-road-data/traffic-signs/v3
            current-state-path: /current-state
            town-code: GM0307

logging:
  level:
    root: INFO
    nu.ndw.nls: DEBUG
graphhopper:
  dir: graphhopper
spring:
  datasource:
    url: jdbc:postgresql://nls-postgres:5432/nls-maps?ApplicationName=nls-accessibility-map-jobs&stringtype=unspecified
    username: nls-maps
    password: nls-maps

