graphhopper:
  dir: /application/graphhopper
jooq:
  schema-validation:
    schema-severity:
      nwb: ERROR
    packages-to-scan:
      - nu.ndw.nls.db.nwb.jooq.generated

org:
  jooq:
    no-logo: true
spring:
  application:
    name: nls-accessibility-map-jobs
  # Disables netty webserver startup
  main:
    web-application-type: none
  config:
    import: "optional:configtree:/application/config/configtree/"
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SELECT 1;
      idle-timeout: 60000
      max-lifetime: 120000
      minimum-idle: 1
      auto-commit: false
  jmx:
    enabled: false
  jooq:
    sql-dialect: Postgres
traffic-sign:
  base-url: https://data.ndw.nu/api/rest/static-road-data/traffic-signs/v3
  current-state-uri: /current-state?status=PLACED
