apiVersion: v1
kind: ConfigMap
metadata:
  name: nls-accessibility-map-api-config
  namespace: nls
data:
  MANAGEMENT_OBSERVATIONS_KEYVALUES_ENVIRONMENT: {{ .Values.environment }}
  NLS_OAUTH2_JWTRESOURCEPROPERTY: app-{{ .Chart.Name }}-{{ .Values.environment }}
  SPRING_APPLICATION_NAME: {{ .Chart.Name }}-{{ .Values.environment }}
  SPRING_MAIN_BANNER_MODE: 'off'
  SPRING_PROFILES_ACTIVE: {{ .Values.environment }}