apiVersion: apps/v1
kind: Deployment
metadata:
  name: nls-accessibility-map-api-deployment
  labels:
    tags.datadoghq.com/service: {{ .Chart.Name }}
    tags.datadoghq.com/env: {{ .Values.environment }}
    tags.datadoghq.com/version: "{{ .Chart.AppVersion }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        ad.datadoghq.com/{{ .Chart.Name }}.logs: '[{"source": "java", "service": "{{ .Chart.Name }}"}]'
        admission.datadoghq.com/java-lib.version: "{{ .Values.datadog.agent.version }}"
      labels:
        app: {{ .Chart.Name }}
        environment: {{ .Values.environment }}
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/service: {{ .Chart.Name }}
        tags.datadoghq.com/env: {{ .Values.environment }}
        tags.datadoghq.com/version: "{{ .Chart.AppVersion }}"
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image:
            ndwnls.azurecr.io/nls-accessibility-map-api:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
          ports:
            - containerPort: 8080
          env:
            {{- /*
            Added as env variable so the dd init container appends the settings instead of an overwrite
            */}}
            - name: JAVA_TOOL_OPTIONS
              value: -XX:MaxRAMPercentage=70 -Dorg.jooq.no-tips=true -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=./heapdumps/
          envFrom:
            - configMapRef:
                name: nls-accessibility-map-api-config
          readinessProbe:
            httpGet:
              path: /api/rest/static-road-data/accessibility-map/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /api/rest/static-road-data/accessibility-map/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 300
            timeoutSeconds: 60
          volumeMounts:
            - mountPath: /application/config
              name: nls-accessibility-map-api-secrets
              readOnly: true
            - mountPath: /application/graphhopper
              name: nls-accessibility-map-api-volume
            - mountPath: /application/heapdumps
              name: nls-accessibility-map-api-heapdump-volume
              subPath: {{ .Chart.Name }}
      volumes:
        - name: nls-accessibility-map-api-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: nls-accessibility-map-api-spc
        - name: nls-accessibility-map-api-volume
          persistentVolumeClaim:
            claimName: nls-accessibility-map-api-pvc
        - name: nls-accessibility-map-api-heapdump-volume
          persistentVolumeClaim:
            claimName: heapdump-pvc-claim
