apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nls-accessibility-map-api-spc
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    # Client id of the azure workload service account "nls-aks-{{ .Values.environment }}-aks-azure-workload-identity.
    # Used to authorise pod access to key vault
    clientID: {{ .Values.secretProviderClass.azureWorkloadClientId }}
    keyvaultName: nls-key-vault-{{ .Values.environment }}
    objects: |
      array:
        - |
          objectName: nls-accessibility-map-api-yaml
          objectAlias: application.yaml
          objectType: secret
        - |
          objectName: nls-datadog-uri
          objectAlias: configtree/management/datadog/metrics/export/uri
          objectType: secret
        - |
          objectName: nls-datadog-apiKey
          objectAlias: configtree/management/datadog/metrics/export/apiKey
          objectType: secret
        - |
          objectName: nls-datadog-applicationKey
          objectAlias: configtree/management/datadog/metrics/export/applicationKey
          objectType: secret
        - |
          objectName: nls-keycloak-url
          objectAlias: configtree/nls/keycloak/url
          objectType: secret
        - |
          objectName: nls-maps-database-password-nls
          objectAlias: configtree/spring/datasource/password
          objectType: secret
    # Tenant ID of Azure Active Directory "ndw"
    tenantId: {{ .Values.secretProviderClass.tenantID }}
