services:
  nls-postgres:
    image: ndwnls.azurecr.io/nls-postgres-it-container:20260225.4
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nls-maps
      - POSTGRES_USER=nls-maps
      - POSTGRES_PASSWORD=nls-maps
    networks:
      - nls-accessibility-map-network

  nls-nwb-schema-manager:
    image: ndwnls.azurecr.io/nls-nwb-schema-manager:20260319.2
    platform: linux/amd64
    environment:
      - SPRING_PROFILES_ACTIVE=build
      - COMMAND=updateNwbSchema
    depends_on:
      - nls-postgres
    networks:
      - nls-accessibility-map-network

  nls-rabbitmq:
    image: ndwnls.azurecr.io/docker.io/library/rabbitmq:4.2.2-management-alpine
    hostname: nls-rabbitmq
    user: rabbitmq
    platform: linux/amd64
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./docker/nls-rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/nls-rabbitmq/load-definitions.json:/etc/rabbitmq/load-definitions.json
    networks:
      - nls-accessibility-map-network

  accessibility-wiremock:
    hostname: accessibility-wiremock
    image: ndwnls.azurecr.io/docker.io/wiremock/wiremock:3.0.0-1
    volumes:
      - ./docker/accessibility-wiremock/extensions:/var/wiremock/extensions

    command: --port 8888 --extensions="nu.ndw.nls.wiremock.extensions.QueryParamToBodyFileTransformer,com.github.masonm.JwtMatcherExtension,com.github.masonm.JwtStubMappingTransformer" --global-response-templating --verbose
    ports:
      - "8888:8888"
    networks:
      - nls-accessibility-map-network

  nls-keycloak:
    image: ndwnls.azurecr.io/quay.io/keycloak/keycloak:26.5.4
    command: start-dev --import-realm
    hostname: nls-keycloak
    environment:
      - KEYCLOAK_ADMIN=nls
      - KEYCLOAK_ADMIN_PASSWORD=nls
      - KC_HOSTNAME=http://localhost:8000/auth
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - KC_HTTP_PORT=8000
      - KC_HTTP_RELATIVE_PATH=/auth
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nls-keycloak/config/realm-export-nls.json:/opt/keycloak/data/import/realm-export-nls.json
      - ./docker/nls-keycloak/dump:/opt/keycloak/data/export/
    networks:
      - nls-accessibility-map-network

networks:
  nls-accessibility-map-network:
    name: nls-accessibility-map-network
