services:
  nls-postgres:
    image: ndwnls.azurecr.io/nls-postgres-it-container:20260722.1@sha256:02c20a29206c89f95da43d205e3e7a6a0fa5081942fc9c0ef16e3d7cd576dd88
    platform: linux/amd64
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 2s
      timeout: 2s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nls-maps
      - POSTGRES_USER=nls-maps
      - POSTGRES_PASSWORD=nls-maps
    networks:
      - nls-accessibility-map-network

  nls-nwb-schema-manager:
    image: ndwnls.azurecr.io/nls-nwb-schema-manager:20260723.2@sha256:71ccc412b850bb83d923cf4c1b41a9114493545fba1a49b21f4b1bad694ce639
    platform: linux/amd64
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - COMMAND=updateNwbSchema
    depends_on:
      nls-postgres:
        condition: service_healthy
    networks:
      - nls-accessibility-map-network

  nls-rabbitmq:
    image: ndwnls.azurecr.io/docker.io/library/rabbitmq:4.2.2-management-alpine@sha256:563b3b81b17cb0b96461ecfe6b23b7eb167dc6b0c4d21dded08617371aa06daa
    hostname: nls-rabbitmq
    user: rabbitmq
    platform: linux/amd64
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5552:5552"
    volumes:
      - ./docker/nls-rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/nls-rabbitmq/load-definitions.json:/etc/rabbitmq/load-definitions.json
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 2s
      timeout: 30s
      retries: 20
      start_period: 10s
    networks:
      - nls-accessibility-map-network
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins

  accessibility-wiremock:
    hostname: accessibility-wiremock
    image: ndwnls.azurecr.io/docker.io/wiremock/wiremock:3.13.2-alpine@sha256:f8c42a38dca3f4a1d7219af11c80438740f39eebb1505b0f029aed743c20e147
    platform: linux/amd64
    volumes:
      - ./docker/accessibility-wiremock/extensions:/var/wiremock/extensions
      - ./docker/accessibility-wiremock/mappings:/home/wiremock/mappings
    command: --port 8888 --extensions="nu.ndw.nls.wiremock.extensions.QueryParamToBodyFileTransformer,com.github.masonm.JwtMatcherExtension,com.github.masonm.JwtStubMappingTransformer" --global-response-templating --verbose
    ports:
      - "8888:8888"
    networks:
      - nls-accessibility-map-network

  initialise-cache-job:
    build:
      context: docker/nls-accessibility-map-job
    environment:
      - SPRING_PROFILES_ACTIVE=dev,job-initialize-cache,docker
      - COMMAND=initializeCache
      - MANAGEMENT_DATADOG_METRICS_EXPORT_ENABLED=false
      - JAVA_TOOL_OPTIONS=-Dorg.jooq.no-tips=true
    depends_on:
      nls-postgres:
        condition: service_started
      nls-nwb-schema-manager:
        condition: service_completed_successfully
    volumes:
      - ./cache:/application/cache
    networks:
      - nls-accessibility-map-network


  nls-keycloak:
    image: ndwnls.azurecr.io/quay.io/keycloak/keycloak:26.6.1@sha256:dea26401d06341095cc4ea9d66896200b55de5ca1daa1d2fcbe58493afa6e0ad
    command: start-dev --import-realm
    hostname: nls-keycloak
    environment:
      - KEYCLOAK_ADMIN=nls
      - KEYCLOAK_ADMIN_PASSWORD=nls
      - KC_HOSTNAME=http://localhost:8000/auth
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - KC_HTTP_PORT=8000
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_HEALTH_ENABLED=true
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nls-keycloak/config/realm-export-nls.json:/opt/keycloak/data/import/realm-export-nls.json
      - ./docker/nls-keycloak/dump:/opt/keycloak/data/export/
    healthcheck:
      test: [ "CMD-SHELL", "/opt/keycloak/bin/kcadm.sh config credentials --server http://localhost:8000/$${KC_HTTP_RELATIVE_PATH}/ --realm master && /opt/keycloak/bin/kcadm.sh get http://localhost:9000/$${KC_HTTP_RELATIVE_PATH}/health" ]
      interval: 2s
      timeout: 30s
      retries: 20
      start_period: 30s
    networks:
      - nls-accessibility-map-network

networks:
  nls-accessibility-map-network:
    name: nls-accessibility-map-network


configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management, rabbitmq_management_agent, rabbitmq_prometheus, rabbitmq_web_dispatch, rabbitmq_stream, rabbitmq_stream_management]."
