hostSuffix: "replaced_by_pipeline"
pods:
  application:
    container:
      resources:
        requests:
          memory: "768Mi"
          cpu: "1000m"
        limits:
          memory: "768Mi"
          cpu: "1000m"
      env:
        javaOptions: -XX:MaxRAMPercentage=70
  database:
    container:
      image: "ndwnls.azurecr.io/nls-postgres-it-container:20260722.1@sha256:02c20a29206c89f95da43d205e3e7a6a0fa5081942fc9c0ef16e3d7cd576dd88"
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "500m"
  mq:
    container:
      image: "ndwnls.azurecr.io/docker.io/library/rabbitmq:4.2.2-management-alpine@sha256:563b3b81b17cb0b96461ecfe6b23b7eb167dc6b0c4d21dded08617371aa06daa"
      resources:
        requests:
          memory: "256Mi"
          cpu: "300m"
        limits:
          memory: "256Mi"
          cpu: "300m"
  oauth:
    container:
      image: "ndwnls.azurecr.io/quay.io/keycloak/keycloak:26.0@sha256:09a381c715ab0b111835b70f2905955274843a219c6f27efb348e4d9f4086858"
      resources:
        requests:
          memory: "768Mi"
          cpu: "500m"
        limits:
          memory: "768Mi"
          cpu: "500m"
  wiremock:
    container:
      image: "ndwnls.azurecr.io/docker.io/wiremock/wiremock:3.13.2-alpine@sha256:f8c42a38dca3f4a1d7219af11c80438740f39eebb1505b0f029aed743c20e147"
      resources:
        requests:
          memory: "256Mi"
          cpu: "300m"
        limits:
          memory: "256Mi"
          cpu: "300m"
  jobs:
    container:
      resources:
        requests:
          memory: "768Mi"
          cpu: "500m"
        limits:
          memory: "768Mi"
          cpu: "500m"
      env:
        javaOptions: -XX:MaxRAMPercentage=70


