apiVersion: v1
kind: ConfigMap
metadata:
  name: nls-accessibility-map-jobs-config
data:
  DD_DATA_STREAMS_ENABLED: "true"
  DD_TRACE_METHODS: picocli.CommandLine[execute]
  MANAGEMENT_OBSERVATIONS_KEYVALUES_ENVIRONMENT: {{ .Values.environment }}
  NU_NDW_NLS_ACCESSIBILITYMAP_TRAFFICSIGNCLIENT_API_URL: {{ .Values.trafficSignApiUrl }}
  SPRING_APPLICATION_NAME: {{ .Chart.Name }}-{{ .Values.environment }}
  SPRING_DATASOURCE_URL: jdbc:postgresql://{{ .Values.application.databaseHost }}/nls-maps?ApplicationName=nls-accessibility-map-jobs&stringtype=unspecified
  SPRING_DATASOURCE_USERNAME: nls
  SPRING_MAIN_BANNER_MODE: 'off'
  SPRING_PROFILES_ACTIVE: {{ .Values.environment }}
