apiVersion: v1
kind: ConfigMap
metadata:
  name: nls-accessibility-map-jobs-config
data:
  LOGGING_LEVEL_NU_NDW_NLS_ACCESSIBILITYMAP: {{ .Values.application.loggingLevelNuNdwNlsAccessibilityMap }}
  MANAGEMENT_OBSERVATIONS_KEYVALUES_ENVIRONMENT: {{ .Values.environment }}
  SPRING_APPLICATION_NAME: {{ .Chart.Name }}-{{ .Values.environment }}
  SPRING_DATASOURCE_URL: jdbc:postgresql://{{ .Values.application.databaseHost }}/nls-maps?ApplicationName=nls-accessibility-map-jobs&stringtype=unspecified
  SPRING_DATASOURCE_USERNAME: nls
  SPRING_MAIN_BANNER_MODE: 'off'
  NU_NDW_NLS_ACCESSIBILITYMAP_JOBS_TRAFFICSIGNS_API_BASE_URL: {{ .Values.trafficSignApiUrl }}
  SPRING_PROFILES_ACTIVE: {{ .Values.environment }}
