apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: nls-accessibility-map-api-pod-restarter
  labels:
    tags.datadoghq.com/service: nls-accessibility-map-api-pod-restarter
    tags.datadoghq.com/env: {{ .Values.environment }}
    tags.datadoghq.com/version: "{{ .Chart.AppVersion }}"
spec:
  jobTargetRef:
    activeDeadlineSeconds: 86400 # Maximum execution time before terminating, includes retries
    backoffLimit: 0 # Number of retries before marking job failed; default 6
    template:
      metadata:
        annotations:
          ad.datadoghq.com/nls-pod-restarter.logs: '[{"source": "java", "service": "nls-accessibility-map-api-pod-restarter"}]'
          admission.datadoghq.com/java-lib.version: "{{ .Values.datadog.agent.version }}"
        labels:
          app: nls-accessibility-map-api-pod-restarter
          environment: {{ .Values.environment }}
          admission.datadoghq.com/enabled: "true"
          tags.datadoghq.com/service: nls-accessibility-map-api-pod-restarter
          tags.datadoghq.com/env: {{ .Values.environment }}
          tags.datadoghq.com/version: "{{ .Chart.AppVersion }}"
      spec:
        serviceAccountName: nls-pod-restarter-service-account
        containers:
          - name: nls-pod-restarter
            resources:
              limits:
                memory: 384Mi
              requests:
                memory: 384Mi
            image: ndwnls.azurecr.io/nls-pod-restarter:{{ .Values.podRestarterVersion }}
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: nls-accessibility-map-api-pod-restarter-config
            env:
              - name: COMMAND
                value: restartPod
              {{- /*
              Added as env variable so the dd init container appends the settings instead of an overwrite
              Application uses about 64MB Heap memory and up to 105MB non-heap. Using Xmx instead of MaxRAMPercentage=70, because
              MaxRAMPercentage causes the Heap to initialize at 256MB, adding non-heap usage of 105MB this is 361MB total memory usage,
              which is too close to the pod limit and probably causes a Kubernetes OOM-kill of which the stats never reach Datadog
              */}}
              - name: JAVA_TOOL_OPTIONS
                value: -Xmx128m -Ddatadog.slf4j.simpleLogger.logFile=System.out -Ddatadog.slf4j.simpleLogger.dateTimeFormat="yyyy-MM-dd HH:mm:ss.SSS"
            volumeMounts:
              - mountPath: /application/config
                name: nls-accessibility-map-api-secrets
                readOnly: true
        volumes:
          - name: nls-accessibility-map-api-secrets
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: nls-accessibility-map-jobs-spc
  pollingInterval: 60 # Default 30 seconds
  successfulJobsHistoryLimit: 2 # Default 100
  maxReplicaCount: 1 # Default 100
  triggers:
    - type: rabbitmq
      metadata:
        queueName: nls_accessibility_map_api_routing_network_updated
        mode: QueueLength
        value: '1' # Tells Keda how many queue messages a single instance processes (default 20)
      authenticationRef:
        name: nls-accessibility-map-api-pod-restarter-trigger-auth
