apiVersion: v1
kind: ConfigMap
metadata:
  name: nls-accessibility-map-api-pod-restarter-config
data:
  DD_DATA_STREAMS_ENABLED: "true"
  DD_TRACE_METHODS: picocli.CommandLine[execute]
  DEPLOYMENT_DEPLOYMENTNAME: 'nls-accessibility-map-api-deployment'
  DEPLOYMENT_NAMESPACE: 'nls'
  MANAGEMENT_OBSERVATIONS_KEYVALUES_ENVIRONMENT: {{ .Values.environment }}
  RABBITMQ_EVENTTYPE: 'accessibility-routing-network-updated'
  RABBITMQ_EXCHANGENAME: 'eventbus'
  RABBITMQ_QUEUE: 'nls_accessibility_map_api_routing_network_updated'
  RABBITMQ_ROUTINGKEYS_0_: 'ndw.nls.accessibility.routing.network.updated'
  SPRING_MAIN_BANNER_MODE: 'OFF'
  SPRING_PROFILES_ACTIVE: {{ .Values.environment }}
