apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: nls-accessibility-map-api-pod-restarter-trigger-auth
spec:
  azureKeyVault:
    podIdentity:
      provider: azure-workload
    secrets:
      - parameter: host
        name: nls-rabbitMQ-uri
    vaultUri: {{ .Values.keyVault.url }}
