apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nls-accessibility-map-jobs-spc
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    # Client ID of user-assigned identity "nls-aks-{{ .Values.environment }}-cluster-agentpool"
    userAssignedIdentityID: {{ .Values.secretProviderClass.userAssignedIdentityID }}
    keyvaultName: nls-key-vault-{{ .Values.environment }}
    objects: |
      array:
        - |
          objectName: nls-accessibility-map-jobs-yaml
          objectAlias: application.yaml
          objectType: secret
        - |
          objectName: nls-datadog-uri
          objectAlias: configtree/management/datadog/metrics/export/uri
          objectType: secret
        - |
          objectName: nls-datadog-apiKey
          objectAlias: configtree/management/datadog/metrics/export/apiKey
          objectType: secret
        - |
          objectName: nls-datadog-applicationKey
          objectAlias: configtree/management/datadog/metrics/export/applicationKey
          objectType: secret
    # Tenant ID of Azure Active Directory "ndw"
    tenantId: {{ .Values.secretProviderClass.tenantID }}
