apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: nls-accessibility-map-api-traffic-sign-analyser-trigger-auth
spec:
  secretTargetRef:
    - parameter: host
      name: nls-keda-secret
      key: broker_url
