# This job can be used to manually re-create the NWB network.
apiVersion: batch/v1
kind: Job
metadata:
  name: nls-accessibility-map-graphhopper-cron-job-manual-init-nwb-job #variable: Configure a descriptive job name and include 'manual' to let others know we are manually running this process
spec:
  # Clean up job after 1 week
  ttlSecondsAfterFinished: 604800
  backoffLimit: 3
  template:
    metadata:
      annotations:
        ad.datadoghq.com/nls-accessibility-map-jobs.logs: '[{"source": "java", "service": "nls-accessibility-map-graphhopper-cron-job-manual-init-nwb-job"}]'
      labels:
        environment: staging #variable: choose staging/production
    spec:
      containers:
        - name: nls-accessibility-map-graphhopper-cron-job
          image: ndwnls.azurecr.io/nls-accessibility-map-graphhopper-job:20240828.4 #variable: pick the version you need
          imagePullPolicy: Always
          resources:
            limits:
              memory: 8Gi
            requests:
              memory: 8Gi
          envFrom:
            - configMapRef:
                name: nls-accessibility-map-jobs-config
          env:
              - name: COMMAND
                value: createOrUpdateNetwork
              - name: JAVA_TOOL_OPTIONS
                value: -XX:MaxRAMPercentage=70 -Dorg.jooq.no-tips=true -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=./heapdumps/
          volumeMounts:
            - mountPath: /application/config
              name: nls-accessibility-map-graphhopper-cron-jobs-secrets
              readOnly: true
            - mountPath: /application/heapdumps
              name: nls-accessibility-map-graphhopper-cron-jobs-heapdump-volume
              subPath: nls-accessibility-map-jobs
            - mountPath: /application/graphhopper
              name: nls-accessibility-map-graphhopper-cron-jobs-volume
      volumes:
        - name: nls-accessibility-map-graphhopper-cron-jobs-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: nls-accessibility-map-jobs-spc
        - name: nls-accessibility-map-graphhopper-cron-jobs-volume
          persistentVolumeClaim:
            claimName: nls-accessibility-map-api-pvc
        - name: nls-accessibility-map-graphhopper-cron-jobs-heapdump-volume
          persistentVolumeClaim:
            claimName: heapdump-pvc-claim
      restartPolicy: Never
