hostSuffix: "replaced_by_pipeline"
pods:
  application:
    container:
      resources:
        requests:
          memory: "768Mi"
          cpu: "200m"
        limits:
          memory: "768Mi"
          cpu: "1000m"
      env:
        javaOptions: -XX:MaxRAMPercentage=70
  database:
    container:
      image: "ndwnls.azurecr.io/nls-postgres-it-container:20250726.2"
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "1000m"
  mq:
    container:
      image: "ndwnls.azurecr.io/docker.io/library/rabbitmq:4.2.2-management-alpine"
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "400m"
  oauth:
    container:
      image: "ndwnls.azurecr.io/quay.io/keycloak/keycloak:26.0"
      resources:
        requests:
          memory: "768Mi"
          cpu: "200m"
        limits:
          memory: "768Mi"
          cpu: "2000m"
  wiremock:
    container:
      image: "ndwnls.azurecr.io/docker.io/wiremock/wiremock:3.13.1-alpine"
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "256Mi"
          cpu: "1000m"
  jobs:
    container:
      resources:
        requests:
          memory: "768Mi"
          cpu: "200m"
        limits:
          memory: "768Mi"
          cpu: "1000m"
      env:
        javaOptions: -XX:MaxRAMPercentage=70


