openapi: 3.0.0

info:
  title: Accessibility Map API
  description: REST API to determine accessible road sections for a given vehicle type
  version: '1'

servers:
  - url: /v1
  - url: /api/rest/static-road-data/accessibility-map/v1

security:
  - iamNdw: [ ]

paths:
  /test/{map}:
    post:
      tags:
        - accessibility-map
      summary: Test endpoint to verify correct code generation
      operationId: testEndpoint
      parameters:
        - $ref: '#/components/parameters/MapTypeParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

components:
  schemas:
    MapType:
      type: string
      enum:
        - nwb
        - fcd
      x-enum-varnames:
        - nwb
        - fcd
      example: nwb
    APIError:
      type: object
      properties:
        message:
          type: string
  parameters:
    MapTypeParam:
      in: path
      name: map
      description: Map Type
      required: true
      schema:
        $ref: '#/components/schemas/MapType'

  securitySchemes:
    iamNdw:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://iam.ndw.nu/auth/realms/ndw/protocol/openid-connect/token
          refreshUrl: https://iam.ndw.nu/auth/realms/ndw/protocol/openid-connect/token
          scopes: { }
