apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      containers:
        - name: database
          image: {{ .Values.pods.database.container.image }}
          imagePullPolicy: IfNotPresent
          resources:
            {{ toYaml .Values.pods.database.container.resources | nindent 12 }}
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: nls-maps
            - name: POSTGRES_PASSWORD
              value: nls-maps
          readinessProbe:
            tcpSocket:
              port: 5432
