apiVersion: batch/v1
kind: Job
metadata:
  name: initialise-cache-job

spec:
  ttlSecondsAfterFinished: 604800
  activeDeadlineSeconds: 86400
  backoffLimit: 3

  template:
    metadata:
      labels:
        app:  initialise-cache-job
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: initialise-cache-job
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
          image: "ndwnls.azurecr.io/nls-accessibility-map-job:{{ $.Chart.AppVersion }}"
          imagePullPolicy: Always
          env:
            - name: COMMAND
              value: initializeCache
            - name: JAVA_TOOL_OPTIONS
              value: -Dspring.profiles.active=acceptance-test,pipeline,job-initialize-cache -DhostSuffix={{ .Values.hostSuffix }} {{ .Values.pods.jobs.container.env.javaOptions }}
          volumeMounts:
            - mountPath: /application/cache
              name: cache

      restartPolicy: OnFailure
      volumes:

        - name: cache
          persistentVolumeClaim:
            claimName: azure-cache-blob-claim
