apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiremock
  template:
    metadata:
      labels:
        app: wiremock
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      containers:
        - name: wiremock
          image: {{ .Values.pods.wiremock.container.image }}
          imagePullPolicy: Always
          args:
            - "--global-response-templating"
            - "--verbose"
          resources:
            {{ toYaml .Values.pods.wiremock.container.resources | nindent 12 }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /__admin/health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /__admin/health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 12
