datadog:
  agent:
    version: v1.45.1
podRestarterVersion: "20250113.1"

mapGenerator:
  cronJobs:
    generateGeoJsonRvvC6:
      name: nls-accessibility-map-generate-rvv-c6-cron-job
      command: generate --export-name=C6 --traffic-sign=C6 --include-only-time-windowed-signs --publish-events --export-type=LINE_STRING_GEO_JSON --export-type=POLYGON_GEO_JSON
      memory: 16Gi
      schedule: "30 3 * * *"
    generateGeoJsonRvvC7:
      name: nls-accessibility-map-generate-rvv-c7-cron-job
      command: generate --export-name=C7 --traffic-sign=C7 --include-only-time-windowed-signs --publish-events --export-type=LINE_STRING_GEO_JSON --export-type=POLYGON_GEO_JSON
      memory: 16Gi
      schedule: "40 3 * * *"
    generateGeoJsonRvvC7B:
      name: nls-accessibility-map-generate-rvv-c7b-cron-job
      command: generate --export-name==C7B --traffic-sign=C7B --include-only-time-windowed-signs --publish-events --export-type=LINE_STRING_GEO_JSON --export-type=POLYGON_GEO_JSON
      memory: 16Gi
      schedule: "50 3 * * *"
    generateGeoJsonRvvC12:
      name: nls-accessibility-map-generate-rvv-c12-cron-job
      command: generate --export-name==C12 --traffic-sign=C12 --include-only-time-windowed-signs --publish-events --export-type=LINE_STRING_GEO_JSON --export-type=POLYGON_GEO_JSON
      memory: 16Gi
      schedule: "0 4 * * *"
    generateGeoJsonRvvC22C:
      name: nls-accessibility-map-generate-rvv-c22c-cron-job
      command: generate --export-name==C22C --traffic-sign=C22C --include-only-time-windowed-signs --publish-events --export-type=LINE_STRING_GEO_JSON --export-type=POLYGON_GEO_JSON
      memory: 16Gi
      schedule: "10 4 * * *"

trafficSignAnalyser:
  name: nls-accessibility-map-traffic-sign-analyser-job
  command: analyse --traffic-signs=C17 --traffic-signs=C18 --traffic-signs=C19 --traffic-signs=C20 --traffic-signs=C21
  memory: 4Gi
  queueName: nls_accessibility_map_api_routing_network_updated_traffic_sign_analyser
