nu:
  ndw:
    nls:
      accessibilitymap:
        trafficsignclient:
          api:
            url: http://accessibility-wiremock-stub:8080/api/rest/static-road-data/traffic-signs/v4
            town-codes: GM0307
        trafficsigns:
          cache:
            fail-on-no-data-on-startup: false
