FROM ndwnls.azurecr.io/docker.io/library/eclipse-temurin:21-jre-jammy AS builder
WORKDIR /builder
COPY application.jar application.jar
RUN java -Djarmode=tools -jar application.jar extract --layers --destination extracted

FROM ndwnls.azurecr.io/docker.io/library/eclipse-temurin:21-jre-jammy

# Add non-privileged user
RUN useradd -u 1000 java

WORKDIR /application

COPY --chown=java:java --from=builder /builder/extracted/dependencies/ ./
COPY --chown=java:java --from=builder /builder/extracted/spring-boot-loader/ ./
COPY --chown=java:java --from=builder /builder/extracted/snapshot-dependencies/ ./
COPY --chown=java:java --from=builder /builder/extracted/application/ ./
COPY --chown=java:java logback-deploy.xml logback-deploy.xml

USER 1000

ENTRYPOINT ["java", "-jar", "application.jar", "$COMMAND"]
