hostSuffix: "replaced_by_pipeline"
hostDatabase: database.${hostSuffix}
hostRabbitMQ: rabbitmq.${hostSuffix}
hostWiremock: wiremock.${hostSuffix}

nu:
  ndw:
    nls:
      accessibilitymap:
        jobs:
          generate:
            root-export-directory: "/application/maps"
        trafficSigns:
          cache:
            folder: "./cache/trafficSigns"

        network:
          cache:
            folder: "./cache/network"
