hostDatabase: localhost
hostRabbitMQ: localhost
hostWiremock: localhost

server:
  port: 8081

spring:
  cloud:
    openfeign:
      micrometer:
        enabled: false
  datasource:
    url: jdbc:postgresql://${hostDatabase}:5432/nls-maps?ApplicationName=nls-accessibility-map-job&stringtype=unspecified
    username: nls-maps
    password: nls-maps
  main:
    web-application-type: servlet
  spring:
    rabbitmq:
      host: ${hostRabbitMQ}

management:
  endpoints:
    web:
      exposure:
        include: health,command,accessibility-map-cache-reload
  endpoint:
    health:
      probes:
        enabled: true
  datadog:
    metrics:
      export:
        enabled: false
  observations:
    annotations:
      enabled: false

nu:
  ndw:
    nls:
      accessibilitymap:
        jobs:
          generate:
            root-export-directory: "./.tmp/map-generation-destination"
            prettyPrintJson: true
        trafficsignclient:
          api:
            url: http://${hostWiremock}:8888/api/rest/static-road-data/traffic-signs/v4
        trafficSigns:
          emission-zone:
            client:
              url: http://${hostWiremock}:8888/api/area/ibbm/emission-zones/v1
          cache:
            folder: "./.tmp/trafficSigns/"
            load-data-on-startup: false
            watch-for-updates: false
        network:
          cache:
            folder: "./.tmp/network"
            load-data-on-startup: false
            watch-for-updates: false
      springboot:
        messaging:
          broker-uri: amqp://guest:guest@${hostRabbitMQ}:5672?heartbeat=300
        job:
          run-as-service: true

nls:
  keycloak:
    url: http://${hostWiremock}:8888/auth
    client-id: nls-accessibility-map-api-service-account

feign:
  client:
    base-url: http://${hostWiremock}:8888/api

logging:
  level:
    root: INFO
    nu.ndw.nls: DEBUG
