hostSuffix: "replaced_by_pipeline"
hostDatabase: database.${hostSuffix}
hostRabbitMQ: rabbitmq.${hostSuffix}
hostWiremock: wiremock.${hostSuffix}

nu:
  ndw:
    nls:
      accessibilitymap:

        network:
          cache:
            folder: "./.tmp/network"
