environment: production

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://nls-postgres-staging.postgres.database.azure.com:5432/nls-maps?ApplicationName=${spring.application.name}&stringtype=unspecified

nu:
  ndw:
    nls:
      accessibilitymap:
        trafficsignclient:
          api:
            url: https://data.ndw.nu/api/rest/static-road-data/traffic-signs/v4

nls:
  keycloak:
    url: "https://nls-key-vault-production.vault.azure.net/"

feign:
  client:
    base:
      url: https://nls.ndw.nu/api
