environment: staging

spring:
  datasource:
    url: jdbc:postgresql://nls-postgres-staging.postgres.database.azure.com:5432/nls-maps?ApplicationName=${spring.application.name}&stringtype=unspecified

nu:
  ndw:
    nls:
      accessibilitymap:
        trafficsignclient:
          currentStateControllerV5:
            url: https://wegkenmerken.staging.ndw.nu/api

nls:
  keycloak:
    url: "https://iam.ndw.nu/auth"

feign:
  client:
    base-url: https://nls.staging.ndw.nu/
