nu:
  ndw:
    nls:
      springboot:
        messaging:
          broker-uri: amqp://guest:guest@localhost:5672?heartbeat=300
          receive:
            - queue: integration_test_accessibility_routing_network_updated
              routingKey: ndw.nls.accessibility.routing.network.updated
              expectedEventTypes:
                - ACCESSIBILITY_ROUTING_NETWORK_UPDATED
