server:
  compression:
    enabled: true
    mime-types: application/json,application/geo+json
  max-http-request-header-size: 50KB
  servlet:
    context-path: /api/rest/static-road-data/accessibility-map

spring:
  application:
    name: nls-accessibility-map-api
  config:
    import: "optional:configtree:/application/config/configtree/"
  liquibase:
    contexts: "main"
    change-log: classpath:/db/changelog/changelog-master.xml
    database-change-log-table: ACC_MAP_DATABASECHANGELOG
    database-change-log-lock-table: ACC_MAP_DATABASECHANGELOGLOCK
    default-schema: public
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SELECT 1;
      idle-timeout: 60000
      max-lifetime: 120000
      minimum-idle: 1
  jackson:
    default-property-inclusion: non_null
  jooq:
    sql-dialect: Postgres
  main:
    banner-mode: off
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${nls.keycloak.url}/realms/ndw
          jwk-set-uri: ${nls.keycloak.url}/realms/ndw/protocol/openid-connect/certs

nu:
  ndw:
    nls:
      accessibilitymap:
        #        cache:
        #          locking:
        network:
          cache:
            name: "Network"
            folder: "./cache/network"
        trafficSigns:
          cache:
            name: "Traffic sign"
            folder: "./cache/trafficSigns"
        messaging:
          stream-queues:
            updateRoadSection:
              stream-queue-name: nls_accessibility_map_update_road_section
              stream-tracking-name: nls-accessibility-map-api-listener-v1
              max-segment-size-in-kb: 5000
              max-age-in-days: 60
              consumer:
                flushInterval-in-seconds: 2
                messageCountBeforeStorage: 1
                exponential-backoff:
                  initial-interval-in-seconds: 1
                  multiplier: 1.5
                  max-interval-in-seconds: 5184000 # 60 days

nls:
  oauth2:
    jwtResourceProperty: app-${spring.application.name}-${environment}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,accessibility-map-cache-reload,messaging
  observations:
    annotations:
      enabled: true
    key-values:
      service: ${spring.application.name}
      environment: ${environment}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    groups-order: DESC
    urls:
      - name: V2 / Latest
        url: /api-docs/v2.yaml
      - name: V1 (Deprecated)
        url: /api-docs/v1.yaml
    path: /api-docs
    show-extensions: true
    show-common-extensions: true

openapi:
  accessibilityMapV1:
    base-path: /v1
  accessibilityMapV2:
    base-path: /v2

logging:
  level:
    root: WARN
    org.jooq.Constants: off # disable Jooq banner
    nu.ndw.nls: WARN
    nu.ndw.nls.accessibilitymap.accessibility: INFO
    nu.ndw.nls.accessibilitymap.accessibility.graphhopper.querygraph.QueryGraphConfigurer: ERROR
