management:
  datadog:
    metrics:
      export:
        enabled: false
nu:
  ndw:
    nls:
      accessibilitymap:
        network:
          cache:
            name: "Network"
            folder: "./.tmp/network"
            load-data-on-startup: false
            watch-for-updates: false
        trafficSigns:
          cache:
            name: "Traffic sign"
            folder: "./.tmp/trafficSigns"
            load-data-on-startup: false
            watch-for-updates: false
