hostSuffix: "replaced_by_pipeline"
hostDatabase: database.${hostSuffix}
hostOauth: oauth.${hostSuffix}
hostRabbitMQ: rabbitmq.${hostSuffix}
hostWireMock: wiremock.${hostSuffix}

spring:
  rabbitmq:
    host: ${hostRabbitMQ}
  datasource:
    url: jdbc:postgresql://${hostDatabase}:5432/nls-maps?ApplicationName=nls-fcd-travel-time-api&stringtype=unspecified

nls:
  keycloak:
    url: http://${hostOauth}/auth
nu:
  ndw:
    nls:
      accessibilitymap:
        jobs:
          generate:
            root-export-directory: "./maps"
        trafficsignclient:
          api:
            url: http://${hostWiremock}:8888/api/rest/static-road-data/traffic-signs/v4
        trafficSigns:
          emission-zone:
            client:
              url: http://${hostWiremock}:8888/api/area/ibbm/emission-zones/v1
          cache:
            folder: "./trafficSigns/"
            load-data-on-startup: false
            watch-for-updates: false
        network:
          cache:
            folder: "./network"
            load-data-on-startup: false
            watch-for-updates: false
      api:
        url: http://${hostWireMock}:8080
      springboot:
        messaging:
          broker-uri: amqp://guest:guest@${hostRabbitMQ}:5672?heartbeat=300
management:
  datadog:
    metrics:
      export:
        enabled: false
