hostSuffix: "replaced_by_pipeline"
hostDatabase: database.${hostSuffix}
hostKeycloak: oauth.${hostSuffix}
hostRabbitMQ: rabbitmq.${hostSuffix}

spring:
  rabbitmq:
    stream:
      host: ${hostRabbitMQ}
    host: ${hostRabbitMQ}

nu:
  ndw:
    nls:
      accessibilitymap:
        trafficSigns:
          cache:
            folder: "./cache/trafficSigns/"
        roadChanges:
          cache:
            folder: "./cache/roadChanges/"
        network:
          cache:
            folder: "./cache/network"
