nu:
  ndw:
    nls:
      springboot:
        messaging:
          broker-uri: amqp://guest:guest@nls-rabbitmq:5672?heartbeat=300

logging:
  level:
    root: INFO
    nu.ndw.nls: DEBUG
graphhopper:
  dir: graphhopper
spring:
  datasource:
    url: jdbc:postgresql://nls-postgres:5432/nls-maps?ApplicationName=nls-accessibility-map-generator-jobs&stringtype=unspecified
    username: nls-maps
    password: nls-maps

