management:
  datadog:
    metrics:
      export:
        enabled: false

  observations:
    annotations:
      enabled: false
nu:
  ndw:
    nls:
      springboot:
        messaging:
          broker-uri: amqp://guest:guest@localhost:5672?heartbeat=300
      accessibilitymap:
        jobs:
          generate:
            root-export-directory: map-generation-destination
            prettyPrintJson: true
logging:
  level:
    root: INFO
    nu.ndw.nls: DEBUG
graphhopper:
  dir: graphhopper
spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/nls-maps?ApplicationName=nls-accessibility-map-generator-jobs&stringtype=unspecified
    username: nls
    password: notingit

