graphhopper:
  dir: /application/graphhopper
  network-name: accessibility_latest

jooq:
  schema-validation:
    schema-severity:
      nwb: ERROR
    packages-to-scan:
      - nu.ndw.nls.db.nwb.jooq.generated
org:
  jooq:
    no-logo: true
spring:
  application:
    name: nls-accessibility-map-generator-jobs
  # Disables netty webserver startup
  main:
    web-application-type: none
  config:
    import: "optional:configtree:/application/config/configtree/"
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SELECT 1;
      idle-timeout: 60000
      max-lifetime: 120000
      minimum-idle: 1
      auto-commit: false
  jmx:
    enabled: false
  jooq:
    sql-dialect: Postgres

nu:
  ndw:
    nls:
      locationdataissuesapi:
        issue:
          url: ${feign.client.base-url}/rest/static-road-data/location-data-issues/v1
        client:
          feign:
            oauth2:
              registration-id: sa-nls-location-data-issues-api
      accessibilitymap:
        jobs:
          generate:
            start-location-latitude: 52.12096528507054
            start-location-longitude: 5.334845116067081
            zone: "Europe/Amsterdam"
            root-export-directory: "/application/maps"
            relative-export-directory-pattern: "'v1/windowTimes/'yyyyMMdd'/geojson/'"
            search-radius-in-meters: 1_000_000_000
            add-traffic-signs-as-points: true
            add-traffic-signs-as-line-strings: true
            traffic-sign-line-string-distance-in-meters: 1
            add-all-road-section-fragments: false
            add-road-segment-fragments-that-are-blocked-in-all-available-directions: true
            add-road-segment-fragments-that-are-accessible-in-all-available-directions: false
            write-road-segment-fragments-that-are-partially-accessible-as-accessible: true
        trafficsignclient:
          api:
            url: https://data.ndw.nu/api/rest/static-road-data/traffic-signs/v4
        trafficsigns:
          cache:
            folder: "trafficsigns"
            file-name-active-version: "active"

      springboot:
        messaging:
          broker-uri: amqp://guest:guest@nls-rabbitmq:5672?heartbeat=300
          publish:
            - routingKey: ndw.nls.maps.accessibility-window-times-rvv-code-c6.geojson.published
              expectedEventType: MAP_GEOJSON_PUBLISHED_EVENT
              eventSubjectType: ACCESSIBILITY_WINDOWS_TIMES_RVV_CODE_C6
            - routingKey: ndw.nls.maps.accessibility-window-times-rvv-code-c7.geojson.published
              expectedEventType: MAP_GEOJSON_PUBLISHED_EVENT
              eventSubjectType: ACCESSIBILITY_WINDOWS_TIMES_RVV_CODE_C7
            - routingKey: ndw.nls.maps.accessibility-window-times-rvv-code-c7b.geojson.published
              expectedEventType: MAP_GEOJSON_PUBLISHED_EVENT
              eventSubjectType: ACCESSIBILITY_WINDOWS_TIMES_RVV_CODE_C7B
            - routingKey: ndw.nls.maps.accessibility-window-times-rvv-code-c12.geojson.published
              expectedEventType: MAP_GEOJSON_PUBLISHED_EVENT
              eventSubjectType: ACCESSIBILITY_WINDOWS_TIMES_RVV_CODE_C12
            - routingKey: ndw.nls.maps.accessibility-window-times-rvv-code-c22c.geojson.published
              expectedEventType: MAP_GEOJSON_PUBLISHED_EVENT
              eventSubjectType: ACCESSIBILITY_WINDOWS_TIMES_RVV_CODE_C22C

management:
  observations:
    annotations:
      enabled: true
