spring:
  datasource:
    url: jdbc:postgresql://nls-postgres:5432/nls-maps?ApplicationName=nls-accessibility-map-generator-jobs&stringtype=unspecified
    username: nls-maps
    password: nls-maps

nu:
  ndw:
    nls:
      springboot:
        messaging:
          broker-uri: amqp://guest:guest@nls-rabbitmq:5672?heartbeat=300
      accessibilitymap:
        trafficsigns:
          cache:
            fail-on-no-data-on-startup: false

logging:
  level:
    root: INFO
    nu.ndw.nls: DEBUG


keycloak:
  server-url: http://accessibility-wiremock-stub:8080/auth
  client-id: nls-accessibility-map-api-service-account
  client-secret: cfe4793c-ddf7-405a-940f-51b43800aed4

feign:
  client:
    base-url: http://accessibility-wiremock-stub:8080/api
